name: Publish Docker image

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: "[1.4.0] Build and push Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          push: true
          build-args: |
            UBUNTU_VERSION=21.04
            MEGA_VERSION=1.4.0-1.1_amd64
          tags: |
            jopplt/megacmd:1.4.0